DROP DATABASE IF EXISTS HOSPITAL;
CREATE DATABASE HOSPITAL;
USE HOSPITAL;

CREATE TABLE IF NOT EXISTS EMPLOYEE
(
	Ecode			INT 			NOT NULL	UNIQUE	AUTO_INCREMENT,
    E_fname 		VARCHAR(255)	NOT NULL,
    E_lname 		VARCHAR(255)	NOT NULL,
    E_dob			DATE,
    E_address		VARCHAR(255),
    E_gender		CHAR(1),
    E_phone			VARCHAR(20),
    Start_date		DATE,
    Related_name	VARCHAR(255),
    Degree_year		INT,
    Department_code	INT,
    CONSTRAINT PRIMARY KEY (Ecode)
);

CREATE TABLE IF NOT EXISTS NURSE
(
	Encode		INT 	NOT NULL,
    CONSTRAINT PRIMARY KEY	(Encode)
);

CREATE TABLE IF NOT EXISTS DOCTOR
(
	Edcode		INT 	NOT NULL,
    CONSTRAINT PRIMARY KEY (Edcode)
);

CREATE TABLE IF NOT EXISTS DEPARTMENT
(
	Depart_code		INT 	NOT NULL	UNIQUE	AUTO_INCREMENT,
    Title			VARCHAR(256),
    Dean_code		INT,
    CONSTRAINT PRIMARY KEY (Depart_code)
);

CREATE TABLE IF NOT EXISTS PATIENT
(
	Pcode			INT 			NOT NULL	UNIQUE	AUTO_INCREMENT,
    P_fname 		VARCHAR(255)	NOT NULL,
    P_lname 		VARCHAR(255)	NOT NULL,
    P_dob			DATE,
    P_gender		CHAR(1),
    P_phone			VARCHAR(20),
	CONSTRAINT PRIMARY KEY (Pcode)
);

CREATE TABLE IF NOT EXISTS OUTPATIENT
(
	Pocode			INT 	NOT NULL,
    CONSTRAINT PRIMARY KEY (Pocode)
);

CREATE TABLE IF NOT EXISTS EXAMINATION
(
	Pocode			INT 	NOT NULL,
    O_fee			FLOAT	NOT NULL,
    O_diagnosis		VARCHAR(255),
    Exam_date		DATE,
    Next_exam_date	DATE,
    Doc_code		INT 	NOT NULL,
    CONSTRAINT PRIMARY KEY	(Pocode, Exam_date, Next_exam_date)
);

CREATE TABLE IF NOT EXISTS INPATIENT
(
	Picode				INT 	NOT NULL,
	Date_of_admission	DATE,
    Sickroom			VARCHAR(10),
    Date_of_discharge	DATE,
    I_fee				FLOAT	NOT NULL,
    Nurse_code			INT 	NOT NULL,
    Doc_code			INT 	NOT NULL,
    CONSTRAINT PRIMARY KEY (Picode)
);

CREATE TABLE IF NOT EXISTS TREATMENT
(
	Picode			INT		NOT NULL,
    T_start_date	DATE,
    T_end_date		DATE,
    Result			VARCHAR(255),
    CONSTRAINT PRIMARY KEY (Picode,T_start_date,T_end_date)
);

CREATE TABLE IF NOT EXISTS MEDICATION
(
	Mcode			INT 			NOT NULL	UNIQUE	AUTO_INCREMENT,
    M_name			VARCHAR(255)	NOT NULL,
    Expiration_date	DATE,
    Effect			VARCHAR(255),
    M_price			FLOAT			NOT NULL,
    CONSTRAINT PRIMARY KEY	(Mcode)
);

CREATE TABLE IF NOT EXISTS IMPORTED_MED
(
	Medcode			INT 	NOT NULL,
    Import_price	FLOAT	NOT NULL,
    Quantity		INT		NOT NULL,
    Import_date		DATE,
    CONSTRAINT PRIMARY KEY (Medcode)
);

CREATE TABLE IF NOT EXISTS PROVIDER
(
	Prcode			INT 			NOT NULL	UNIQUE	AUTO_INCREMENT,
    Pr_name			VARCHAR(255)	NOT NULL,
    Pr_address		VARCHAR(255),
    Pr_phone		VARCHAR(20),
    CONSTRAINT PRIMARY KEY	(Prcode)
);

CREATE TABLE IF NOT EXISTS PROVIDE
(
	Procode			INT		NOT NULL,
    Medprocode		INT		NOT NULL,
    CONSTRAINT PRIMARY KEY (Procode, Medprocode)
);

CREATE TABLE IF NOT EXISTS T_CONTAIN
(
	Pincode			INT NOT NULL,
    Medincode		INT NOT NULL,
    CONSTRAINT PRIMARY KEY (Pincode, Medincode)
);

CREATE TABLE IF NOT EXISTS E_CONTAIN
(
	Poutcode		INT NOT NULL,
    Medoutcode		INT NOT NULL,
    CONSTRAINT PRIMARY KEY (Poutcode, Medoutcode)
);

CREATE TABLE IF NOT EXISTS USER
(
	id				VARCHAR(255)	NOT NULL	UNIQUE,
    password		VARCHAR(255)	NOT NULL,
    userType		INT				NOT NULL,
    PRIMARY KEY (id)
);


