ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FOREIGN KEY (Department_code) REFERENCES DEPARTMENT(Depart_code)
		ON UPDATE CASCADE
		ON DELETE SET NULL;
        
ALTER TABLE NURSE
ADD CONSTRAINT FOREIGN KEY (Encode) REFERENCES EMPLOYEE(Ecode)
		ON UPDATE CASCADE
        ON DELETE CASCADE;

ALTER TABLE DOCTOR
ADD CONSTRAINT FOREIGN KEY (Edcode) REFERENCES EMPLOYEE(Ecode)
		ON UPDATE CASCADE
        ON DELETE CASCADE;

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FOREIGN KEY (Dean_code) REFERENCES DOCTOR(Edcode)
			ON UPDATE CASCADE
			ON DELETE SET NULL;
            
ALTER TABLE OUTPATIENT
ADD CONSTRAINT FOREIGN KEY (Pocode) REFERENCES PATIENT(Pcode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT;
        
ALTER TABLE EXAMINATION
ADD CONSTRAINT FOREIGN KEY (Pocode) REFERENCES OUTPATIENT(Pocode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT,
ADD	CONSTRAINT FOREIGN KEY (Doc_code) REFERENCES DOCTOR(Edcode)
		ON UPDATE CASCADE
        ON DELETE NO ACTION;

ALTER TABLE INPATIENT
ADD CONSTRAINT FOREIGN KEY (Picode) REFERENCES PATIENT(Pcode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT,
ADD CONSTRAINT FOREIGN KEY (Nurse_code) REFERENCES NURSE(Encode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT,
ADD CONSTRAINT FOREIGN KEY (Doc_code) REFERENCES DOCTOR(Edcode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT;
        
ALTER TABLE PROVIDE
ADD CONSTRAINT FOREIGN KEY (Procode) REFERENCES PROVIDER(Prcode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT,
ADD CONSTRAINT FOREIGN KEY (Medprocode) REFERENCES MEDICATION(Mcode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT;

ALTER TABLE TREATMENT
ADD CONSTRAINT FOREIGN KEY (Picode) REFERENCES INPATIENT(Picode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT;

ALTER TABLE T_CONTAIN
ADD CONSTRAINT FOREIGN KEY (Pincode) REFERENCES TREATMENT(Picode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT,
ADD CONSTRAINT FOREIGN KEY (Medincode) REFERENCES MEDICATION(Mcode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT;
        
ALTER TABLE E_CONTAIN    
ADD CONSTRAINT FOREIGN KEY (Poutcode) REFERENCES EXAMINATION(Pocode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT,
ADD CONSTRAINT FOREIGN KEY (Medoutcode) REFERENCES MEDICATION(Mcode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT;
    
ALTER TABLE IMPORTED_MED
ADD CONSTRAINT FOREIGN KEY (Medcode) REFERENCES MEDICATION(Mcode)
		ON UPDATE CASCADE
        ON DELETE RESTRICT;